export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />

      {/* Google Fonts */}
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        cross-origin="true"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Assistant:wght@200..800&family=Lora:ital,wght@0,400..700;1,400..700&display=swap"
        rel="stylesheet"
      />
    </>
  );
}
