import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import Head from "./Head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Head />
      </head>
      <body className={`${lora.variable}`}>{children}</body>
    </html>
  );
}
